version: "3.8"

services:
  citystreetdata:
    depends_on:
      - cityctreetdataDB
    build:
      context: .
    container_name: city-street-data
    hostname: city-street-data
    networks:
      - mynet
    ports:
      - 80:8080
    environment:
      - PGUSER=${PGUSER:-user}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-5432}
      - PGDATABASE=${PGDATABASE:-mydb}
    deploy:
      restart_policy:
        condition: on-failure
  citystreetdataDB:
    image: postgis/postgis:17-3.5
    container_name: postgis
    hostname: db
    networks:
      - mynet
    ports:
      - 5432:5432
      - 8080:8080
    volumes:
      - postgis
    command: start-single-node 

volumes:
  postgis:

networks:
  mynet:
    driver: bridge
